version: "3.3"
services:
  groupincome:
    build: .
    command: grunt dev
    # TODO: don't forget to make these ports configurable and in sync with Gruntfile.js
    #       See also related issue #71.
    ports:
      - "127.0.0.1:8000:8000"   # http server
      - "127.0.0.1:3000:3000"   # api server
      - "127.0.0.1:35729:35729" # livereload
    volumes:
      - .:/opt
    tty: true
